spring.profiles.active=local
spring.application.name=termonal

spring.task.scheduling.shutdown.await-termination=true
spring.task.scheduling.shutdown.await-termination-period=10ms

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

supabase.project=postgres.ksnfkoqhzziucwkoownn
supabase.host=aws-0-sa-east-1.pooler.supabase.com:5432

spring.datasource.url=jdbc:postgresql://${supabase.host}/postgres?user=${supabase.project}&password=${supabase.password}&sslmode=require