spring.profiles.active=local
spring.application.name=termonal

spring.task.scheduling.shutdown.await-termination=true
spring.task.scheduling.shutdown.await-termination-period=10ms

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000

supabase.project=postgres.ksnfkoqhzziucwkoownn
supabase.host=aws-0-sa-east-1.pooler.supabase.com:6543

spring.datasource.url=jdbc:postgresql://${supabase.host}/postgres?user=${supabase.project}&password=${supabase.password}&sslmode=require